source('R/kpl.R')
id <- function(x) diag(1, NROW(x))
p1 <- function(x) ply(x, degree=1)
p2 <- function(x) ply(x, degree=2)
p3 <- function(x) ply(x, degree=3)
ga <- function(x) gau(x, sigma=1.)
lp <- function(x) lap(x)
s1 <- function(x) sin(1 * pi * x)
s2 <- function(x) sin(2 * pi * x)
sg <- function(x) 1/(1 + exp(-x))
ex <- exp
