source('R/kpl.R')
id <- function(x) diag(1, NROW(x))
p1 <- function(x) ply(x, degree=1)
p2 <- function(x) ply(x, degree=2)
p3 <- function(x) ply(x, degree=3)
ga <- function(x) gau(x)
lp <- function(x) lap(x)
s1 <- function(x) sin(1 * pi * x)
s2 <- function(x) sin(2 * pi * x)
sg <- function(x) 1/(1 + exp(-x))

source('R/utl.R')
st <- function(x) ndc(x, qt, df=10)
bn <- function(x) ndc(x, qbinom, size=1, prob=.5)
ps <- function(x) ndc(x, qpois, lambda=1)
ex <- function(x) ndc(x, qexp, rate=1)
ca <- function(x) ndc(x, qcauchy, scale=.1)
ch <- function(x) ndc(x, qchisq, df=1)
