// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// knl_mnq
List knl_mnq(arma::dmat y, List V, arma::dmat P, arma::dvec psd);
RcppExport SEXP _knn_knl_mnq(SEXP ySEXP, SEXP VSEXP, SEXP PSEXP, SEXP psdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dmat >::type y(ySEXP);
    Rcpp::traits::input_parameter< List >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::dvec >::type psd(psdSEXP);
    rcpp_result_gen = Rcpp::wrap(knl_mnq(y, V, P, psd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_knn_knl_mnq", (DL_FUNC) &_knn_knl_mnq, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_knn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
