// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// knl_mnq_cpp
List knl_mnq_cpp(arma::dmat y, List V, arma::dmat P);
RcppExport SEXP _knn_knl_mnq_cpp(SEXP ySEXP, SEXP VSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dmat >::type y(ySEXP);
    Rcpp::traits::input_parameter< List >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::dmat >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(knl_mnq_cpp(y, V, P));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_knn_knl_mnq_cpp", (DL_FUNC) &_knn_knl_mnq_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_knn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
