# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kernel MINQUE
#'
#' Only explicit kernels, no fixed effect, no implicit product kernels
#' from random effect either.
#' Multiply a number by two
#' 
#' @param v r-list, of the kernels
#' @param P matrix, of each column is a contrast of VCs
#' @export
mnq <- function(v, p) {
    .Call('_knn_mnq', PACKAGE = 'knn', v, p)
}

