# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gradient over variance components
#'
#'
#' @param W a L-Q matrix, Q sets of variance components;
#' @param K a list of L kernel matrices;
#' @param Y a N-Q matrix of Q responses;
NULL

