# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kernel MINQUE
#'
#' Only explicit kernels without fixed effect, no implicit product kernels
#' from random effect either.
#' 
#' @param V a list of k kernel matrices matched to k variance components.
#' @param P a m-k matrix, each row is a contrast of k variance components.
#' @export
knl_mnq <- function(y, V, P, psd) {
    .Call('_knn_knl_mnq', PACKAGE = 'knn', y, V, P, psd)
}

